name: 'Auto Assign Action'
description: 'Add reviewers to pull requests when pull requests are opened.'
author: 'Kentaro Matsushita'
inputs:
  repo-token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: false
  configuration-path:
    description: 'A path for the auto-assign configuration'
    default: '.github/auto_assign.yml'
  configuration:
    description: 'Directly give auto-assign configuration as a variable. This overrides whatever is set in the configuration file and expects the same syntax'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'user-plus'
  color: 'blue'
