name: 'Auto Assign Action'
description: 'Add reviewers to pull requests when pull requests are opened.'
author: 'Arush Shankar'
inputs:
  repo-token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: false
  configuration-path:
    description: 'A path for the auto-assign configuration'
    default: '.github/auto_assign.yml'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'user-plus'
  color: 'blue'
